//! Build script: scan `benchmarks/ds4_msl/emitted/` for `.metal` files
//! and bake them into a generated `kernel_sources.rs` consumed by the
//! crate. Also bake an `ANTIREZ_BRIDGE_SOURCE` constant — a single
//! concatenated MSL string assembled from `../upstream/ds4/metal/`
//! with the antirez `host_name("kernel_*")` strings renamed to our
//! `ds4_kernel_*` / `ds4_dsv4_*` prefix convention. This is the M4
//! bridge that unblocks decode-critical pipelines whose emitter-side
//! `.metal` files are not yet generated (see task #219).
//!
//! Runs on Linux and macOS identically (no Metal toolchain needed
//! here; the actual `MTLLibrary` compilation happens at runtime on Mac
//! via `device.new_library_with_source`).

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let emitted_dir = manifest_dir
        .join("..")
        .join("..")
        .join("benchmarks")
        .join("ds4_msl")
        .join("emitted");

    println!("cargo:rerun-if-changed={}", emitted_dir.display());

    let mut entries: Vec<(String, String)> = Vec::new();

    if emitted_dir.is_dir() {
        for entry in fs::read_dir(&emitted_dir).unwrap() {
            let path = entry.unwrap().path();
            if path.extension().and_then(|s| s.to_str()) != Some("metal") {
                continue;
            }
            let name = path.file_stem().unwrap().to_str().unwrap().to_string();
            let src = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("failed to read {}: {}", path.display(), e));
            println!("cargo:rerun-if-changed={}", path.display());
            entries.push((name, src));
        }
    } else {
        println!(
            "cargo:warning=ds4_metal: emitted MSL dir not found at {} — \
             KERNEL_SOURCES will be empty",
            emitted_dir.display()
        );
    }

    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs — do not edit.\n");
    out.push_str("// Source: benchmarks/ds4_msl/emitted/*.metal\n\n");
    out.push_str("pub const KERNEL_SOURCES: &[(&str, &str)] = &[\n");
    for (name, src) in &entries {
        out.push_str(&format!("    ({name:?}, {src:?}),\n"));
    }
    out.push_str("];\n\n");

    // ── antirez bridge ────────────────────────────────────────────────
    let bridge = build_antirez_bridge(&manifest_dir);
    out.push_str("pub const ANTIREZ_BRIDGE_SOURCE: &str = ");
    out.push_str(&format!("{:?}", bridge));
    out.push_str(";\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("kernel_sources.rs"), out).unwrap();
}

/// Build the antirez bridge MSL source by concatenating the upstream
/// `.metal` files (in the order antirez itself uses), prepending the
/// preamble (macros + `block_q8_0` struct), and renaming every
/// `host_name("kernel_...")` / `host_name("kernel_dsv4_...")` to the
/// `ds4_kernel_*` / `ds4_dsv4_*` convention expected by the registry.
///
/// Looks for upstream at:
///   1. `$DS4_UPSTREAM_DIR/metal/*.metal` if env set
///   2. `<workspace>/benchmarks/ds4_msl/upstream/ds4/metal/`
///   3. `<manifest>/../../../ascend-rs-priv/benchmarks/ds4_msl/upstream/ds4/metal/`
///
/// If upstream is missing, returns the preamble alone — at runtime
/// pipeline lookups for unbridged kernels will fail with a clear
/// `pipeline not loaded` error.
fn build_antirez_bridge(manifest_dir: &Path) -> String {
    let upstream = locate_upstream(manifest_dir);
    let metal_dir = upstream.join("metal");

    let preamble = "\
#include <metal_stdlib>
using namespace metal;

#define MAX(x, y) ((x) > (y) ? (x) : (y))
#define MIN(x, y) ((x) < (y) ? (x) : (y))
#define SWAP(x, y) { auto tmp = (x); (x) = (y); (y) = tmp; }
#define QK8_0 32
#define N_SIMDWIDTH 32
#define N_R0_Q8_0 2
#define N_SG_Q8_0 4
#define FC_MUL_MV 600
#define FC_MUL_MM 700
#define FC_BIN 1300
#define FOR_UNROLL(x) _Pragma(\"clang loop unroll(full)\") for (x)
#ifndef M_PI_F
#define M_PI_F 3.14159265358979323846f
#endif

enum ds4_sort_order {
    DS4_SORT_ORDER_ASC,
    DS4_SORT_ORDER_DESC,
};

struct block_q8_0 {
    half d;
    int8_t qs[QK8_0];
};

";

    let mut source = String::from(preamble);

    // Pre-scan bridge_shims so we can skip rewriting any antirez raw
    // kernel whose target (rewritten) symbol is already provided by a
    // shim. This avoids duplicate-symbol MSL compile errors when a
    // shim and a raw antirez kernel coincidentally land on the same
    // ds4_* name after rewrite (e.g. shim
    // `ds4_dsv4_qkv_rms_norm_f32_4` + antirez raw
    // `kernel_dsv4_qkv_rms_norm_f32_4`).
    //
    // The shims dir is `<upstream>/../../bridge_shims` — same path
    // the appender at the bottom of this function uses.
    let shim_symbols = upstream
        .parent()
        .and_then(Path::parent)
        .map(|p| p.join("bridge_shims"))
        .filter(|p| p.is_dir())
        .map(|p| collect_shim_symbols(&p))
        .unwrap_or_default();

    // Order matches antirez's required_sources list in ds4_metal.m so
    // template instantiations follow their declarations.
    const ORDER: &[&str] = &[
        "flash_attn.metal",
        "dense.metal",
        "moe.metal",
        "dsv4_hc.metal",
        "unary.metal",
        "dsv4_kv.metal",
        "dsv4_rope.metal",
        "dsv4_misc.metal",
        "argsort.metal",
        "cpy.metal",
        "concat.metal",
        "get_rows.metal",
        "sum_rows.metal",
        "softmax.metal",
        "repeat.metal",
        "glu.metal",
        "norm.metal",
        "bin.metal",
        "set_rows.metal",
    ];

    if !metal_dir.is_dir() {
        println!(
            "cargo:warning=ds4_metal: antirez upstream metal dir not found at {} — \
             ANTIREZ_BRIDGE_SOURCE will be preamble-only",
            metal_dir.display()
        );
        return source;
    }

    for name in ORDER {
        let path = metal_dir.join(name);
        match fs::read_to_string(&path) {
            Ok(body) => {
                println!("cargo:rerun-if-changed={}", path.display());
                source.push_str(&format!("\n// ──── {name} ────\n"));
                // Two rewrite axes — apply both per-file:
                //  1. Rewrite every `host_name("kernel_X")` →
                //     `host_name("ds4_kernel_X")` (or `ds4_dsv4_X`).
                //  2. For every `kernel void kernel_X(` whose name does
                //     NOT appear as a C++ template reference elsewhere
                //     in the file (i.e. it is genuinely raw-named, not a
                //     template definition that gets instantiated via
                //     `template kernel … kernel_X<…>;`), rewrite the
                //     declaration too. This is the right per-kernel
                //     rule: kernels with template instantiations have
                //     their host_name controlled by the attribute line,
                //     while raw-named kernels use the C++ name as the
                //     host_name and must be rewritten in-place.
                let s1 = rename_host_names_attrs_only(&body);
                let s2 = rewrite_raw_named_kernels(&s1, &shim_symbols);
                source.push_str(&s2);
                source.push('\n');
            }
            Err(e) => {
                println!(
                    "cargo:warning=ds4_metal: failed to read {} ({}) — \
                     ANTIREZ_BRIDGE_SOURCE will be incomplete",
                    path.display(),
                    e
                );
            }
        }
    }

    // Append bridge shims (kernels that the registry needs but antirez
    // does not provide directly — e.g. fused composers like
    // `ds4_dsv4_qkv_rms_norm_f32_4`). Each shim is a standalone .metal
    // file under `benchmarks/ds4_msl/bridge_shims/`; the file is
    // expected to declare its kernel with the final `ds4_*` host_name
    // already (no rename pass).
    let shims_dir = upstream
        .parent()
        .and_then(Path::parent)
        .map(|p| p.join("bridge_shims"))
        .filter(|p| p.is_dir());
    if let Some(dir) = shims_dir {
        let mut shims: Vec<PathBuf> = fs::read_dir(&dir)
            .ok()
            .into_iter()
            .flatten()
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("metal"))
            .collect();
        shims.sort();
        for path in shims {
            match fs::read_to_string(&path) {
                Ok(body) => {
                    println!("cargo:rerun-if-changed={}", path.display());
                    let name = path.file_name().and_then(|s| s.to_str()).unwrap_or("shim");
                    source.push_str(&format!("\n// ──── shim: {name} ────\n"));
                    source.push_str(&body);
                    source.push('\n');
                }
                Err(e) => {
                    println!(
                        "cargo:warning=ds4_metal: failed to read shim {} ({})",
                        path.display(),
                        e
                    );
                }
            }
        }
    }

    source
}

fn locate_upstream(manifest_dir: &Path) -> PathBuf {
    if let Ok(p) = env::var("DS4_UPSTREAM_DIR") {
        return PathBuf::from(p);
    }
    // crates/ds4_metal -> crates -> workspace
    let workspace = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("manifest path has 2 parents")
        .to_path_buf();
    let workspace_upstream = workspace.join("benchmarks/ds4_msl/upstream/ds4");
    if workspace_upstream.join("metal").is_dir() {
        return workspace_upstream;
    }

    // Legacy layout used by older local checkouts:
    // crates/ds4_metal -> crates -> ascend-rs-ds4 -> $HOME.
    let home = manifest_dir
        .parent()
        .and_then(Path::parent)
        .and_then(Path::parent)
        .expect("manifest path has 3 parents")
        .to_path_buf();
    home.join("ascend-rs-priv/benchmarks/ds4_msl/upstream/ds4")
}

/// For files with `[[host_name(...)]]` attributes: only rewrite the
/// host_name strings. The C++ function names stay intact so explicit
/// template instantiations like `template kernel kernel_X<float>;`
/// continue to compile.
fn rename_host_names_attrs_only(src: &str) -> String {
    let s1 = src.replace("host_name(\"kernel_dsv4_", "host_name(\"ds4_dsv4_");
    s1.replace("host_name(\"kernel_", "host_name(\"ds4_kernel_")
}

/// For each `kernel void kernel_X(` declaration in `src`, check whether
/// `kernel_X` appears anywhere else in the file as a C++ template
/// reference (`kernel_X<…>` or `decltype(kernel_X<…>)`). If so, the
/// kernel is a template definition whose host_name is set by an
/// accompanying `[[host_name(...)]]` instantiation line — leave it
/// alone. If not, it is a raw-named kernel whose C++ name IS its
/// host_name; rewrite `kernel_X` to `ds4_kernel_X` (or `ds4_dsv4_X`).
///
/// `shim_symbols` is the set of ds4_* kernel symbols already defined
/// by `bridge_shims/*.metal`; if the would-be rewrite target collides
/// with one of those, skip the rename (the shim wins). This avoids
/// duplicate-symbol MSL compile errors when a shim provides a
/// hand-tuned override of an antirez raw kernel.
fn rewrite_raw_named_kernels(src: &str, shim_symbols: &[String]) -> String {
    let needle = "kernel void kernel_";
    let mut result = src.to_string();
    for (start, _) in src.match_indices(needle).collect::<Vec<_>>() {
        let after = &src[start + needle.len()..];
        let name_end = match after.find('(') {
            Some(e) => e,
            None => continue,
        };
        let raw_name = after[..name_end].trim_end();
        if raw_name.is_empty() || raw_name.contains(|c: char| c.is_whitespace()) {
            continue;
        }
        let tmpl_ref = format!("kernel_{}<", raw_name);
        let decl_ref = format!("decltype(kernel_{}<", raw_name);
        if src.contains(&tmpl_ref) || src.contains(&decl_ref) {
            continue;
        }
        let target = if let Some(rest) = raw_name.strip_prefix("dsv4_") {
            format!("ds4_dsv4_{}", rest)
        } else {
            format!("ds4_kernel_{}", raw_name)
        };
        if shim_symbols.iter().any(|s| s == &target) {
            // A bridge_shim already defines this symbol — leave the
            // antirez declaration alone (still `kernel_X`) so MSL
            // doesn't see two definitions of `target`.
            println!(
                "cargo:warning=ds4_metal: antirez raw kernel `kernel_{}` \
                 shadowed by bridge_shim `{}` — skipping rewrite",
                raw_name, target
            );
            continue;
        }
        let old = format!("kernel void kernel_{}(", raw_name);
        let new = format!("kernel void {}(", target);
        result = result.replacen(&old, &new, 1);
    }
    result
}

/// Walk `<shims_dir>/*.metal` and extract the set of
/// `kernel void <symbol>(` definitions. Returns an empty vec if the
/// directory has no readable shims.
fn collect_shim_symbols(shims_dir: &Path) -> Vec<String> {
    let mut out = Vec::new();
    let entries = match fs::read_dir(shims_dir) {
        Ok(e) => e,
        Err(_) => return out,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("metal") {
            continue;
        }
        let body = match fs::read_to_string(&path) {
            Ok(b) => b,
            Err(_) => continue,
        };
        let needle = "kernel void ";
        for (idx, _) in body.match_indices(needle) {
            let after = &body[idx + needle.len()..];
            let end = match after.find('(') {
                Some(e) => e,
                None => continue,
            };
            let name = after[..end].trim();
            if !name.is_empty() && !name.contains(char::is_whitespace) {
                out.push(name.to_string());
            }
        }
    }
    out
}
